name: ci

defaults:
  #if: "!contains(github.event.head_commit.message, 'skip ci')"  # SKIP
  run:
    # Use a bash shell so we can use the same syntax for environment variable
    # access regardless of the host operating system
    shell: bash -e -x {0}

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  PROJ_PFX_TARGET: ryml-
  PROJ_PFX_CMAKE: RYML_
  CMAKE_FLAGS: -DRYML_TEST_SUITE=ON
  NUM_JOBS_BUILD: # 4

jobs:

  #----------------------------------------------------------------------------
  test_api:
    continue-on-error: true
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {bt: Release, os: ubuntu-18.04}
          - {bt: Release, os: windows-2019}
          - {bt: Release, os: macos-11.0}
    env: {STD: "${{matrix.std}}", CXX_: "${{matrix.cxx}}", BT: "${{matrix.bt}}", BITLINKS: "${{matrix.bitlinks}}", VG: "${{matrix.vg}}", SAN: "${{matrix.san}}", LINT: "${{matrix.lint}}", OS: "${{matrix.os}}",
          API: ON, CMAKE_FLAGS: "-DRYML_DEV=ON -DRYML_BUILD_API=ON -DRYML_API_TESTS=ON -DRYML_API_BENCHMARKS=OFF"}
    steps:
      - {name: checkout, uses: actions/checkout@v2, with: {submodules: recursive, fetch-depth: 0}}
      - {name: python3, uses: actions/setup-python@v2, with: {python-version: 3.7}}
      - {name: install requirements, run: source .github/reqs.sh && c4_install_test_requirements $OS}
      - {name: show info, run: source .github/setenv.sh && c4_show_info && which swig }
      - name: api-shared64-configure---------------------------------------------------
        run: source .github/setenv.sh && c4_cfg_test shared64
      - name: api-shared64-python-build
        run: |
            source .github/setenv.sh
            cd api/python
            pip install -v -r requirements.txt
            find
            python -c "from ryml.version import version as v; print('Installed version:', v)"
      - name: api-shared64-python-test
        run: |
            source .github/setenv.sh
            c4_build_target shared64 ryml-api-test-python3
